name: CI with Composer scripts
on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'
      - 'composer.json'
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: "PHP linter - ${{ matrix.php }}"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      - name: "Run PHP lint"
        run: find .*.php *.php Classes Configuration Tests -name '*.php' -print0 | xargs -r -0 -n 1 -P 4 php -l

  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        command:
          - "composer:normalize"
          - "composer:psr-verify"
          - "php:ecs"
          - "php:rector"
          - "php:fractor"
          - "yaml:lint"
          - "xliff:lint"
        php: [8.2]

    name: "Code quality checks"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
          tools: composer:v2

      - name: "Show Composer version"
        run: composer --version

      - name: "Show the Composer configuration"
        run: composer config --global --list

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v4
        with:
          key: "php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php }}-composer-\n"

      - name: "Install Composer dependencies"
        run: composer install --no-progress

      - name: "List Installed Dependencies"
        run: composer show -D

      - name: "Run command"
        run: composer ci:${{ matrix.command }}
